### ISSUE TITLE
Add timezone / date format option in 'Settings' area

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-mobile#16]
Allow users to select their date / time format.

**Comment by nileshbhingaradiya** [comment]
via Hubstaff
User: Nilesh Patel

Project: bluecherry mobile - https://app.hubstaff.com/projects/1637760
Date Range: 09/06/21 - 09/16/21
Work session total: 12:00:00
Billable: Yes

Project: bluecherry mobile - https://app.hubstaff.com/projects/1637760
Date Range: 09/22/21 - 09/28/21
Work session total: 2:11:59
Billable: No

Grand total: 14:11:59
