### ISSUE TITLE
Add previous / next event buttons during event

### ISSUE THREAD

**Issue by curtishall** [bluecherrydvr/bluecherry-mobile#21]
Bottom corner of each side of the cider I window

**Comment by nileshbhingaradiya** [comment]
it's fixed please check it  https://share.vidyard.com/watch/9V2QJ5ePKDo2gTR7QtqQn9?

**Comment by nileshbhingaradiya** [comment]
via Hubstaff
User: Nilesh Patel

Project: bluecherry mobile - https://app.hubstaff.com/projects/1637760
Date Range: 08/30/21 - 09/02/21
Work session total: 7:00:00
Billable: Yes

Project: bluecherry mobile - https://app.hubstaff.com/projects/1637760
Date Range: 09/01/21 - 09/01/21
Work session total: 4:00:00
Billable: No

Grand total: 11:00:00
